version: "3"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "${APP_PORT:?err}:80"
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/html
    depends_on:
      - app

  app:
    build: .docker/php
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
