version: "3"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
      MYSQL_DATABASE: ${MYSQL_DATABASE:?err}
      MYSQL_USER: ${MYSQL_USER:?err}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?err}
    ports:
      - ${MYSQL_PORT-3306}:3306
    volumes:
      - ./.docker/mysql-data:/var/lib/mysql

  app:
    build: .docker/php
    ports:
      - 9000:9000
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
    links:
      - db:db

  nginx:
    image: nginx:stable-alpine
    ports:
      - ${APP_PORT-8080}:80
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/html
    depends_on:
      - app
