controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

create_hash:
    path: /api/hash/{entry}
    controller: App\Controller\HashController::create
    methods:
        - POST
